-- MySQL Script generated by MySQL Workbench
-- 09/01/17 22:50:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema behbes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema behbes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `behbes` DEFAULT CHARACTER SET utf8 ;
USE `behbes` ;

-- -----------------------------------------------------
-- Table `behbes`.` Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.` Users` ;

CREATE TABLE IF NOT EXISTS `behbes`.` Users` (
  `UserID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(36) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Salt` VARCHAR(45) NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45),
  `RegisterTimeStamp` TIMESTAMP ,
  `BabyID` INT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`Illnesses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`Illnesses` ;

CREATE TABLE IF NOT EXISTS `behbes`.`Illnesses` (
  `IllnessID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `NaturalRemedies` VARCHAR(45) NOT NULL,
  `ConventionalRemedies` VARCHAR(45) NOT NULL,
  `Resources` VARCHAR(45) NULL,
  PRIMARY KEY (`IllnessID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`Symptoms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`Symptoms` ;

CREATE TABLE IF NOT EXISTS `behbes`.`Symptoms` (
  `SymptomID` INT NOT NULL AUTO_INCREMENT,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`SymptomID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`SymptomIllness`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`SymptomIllness` ;

CREATE TABLE IF NOT EXISTS `behbes`.`SymptomIllness` (
  `SymptomID` INT NOT NULL,
  `IllnessID` INT NOT NULL,
  PRIMARY KEY (`SymptomID`, `IllnessID`),
  INDEX `illnessID_idx` (`IllnessID` ASC),
  CONSTRAINT `SymptomID`
    FOREIGN KEY (`SymptomID`)
    REFERENCES `behbes`.`Symptoms` (`SymptomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `illnessID`
    FOREIGN KEY (`IllnessID`)
    REFERENCES `behbes`.`Illnesses` (`IllnessID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`Baby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`Baby` ;

CREATE TABLE IF NOT EXISTS `behbes`.`Baby` (
  `BabyID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Sex` VARCHAR(6) NULL,
  `ParentID` INT UNSIGNED NULL,
  PRIMARY KEY (`BabyID`),
  INDEX `UserID_idx` (`ParentID` ASC),
  CONSTRAINT `UserID`
    FOREIGN KEY (`ParentID`)
    REFERENCES `behbes`.` Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`History`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`History` ;

CREATE TABLE IF NOT EXISTS `behbes`.`History` (
  `HistoryID` INT NOT NULL AUTO_INCREMENT,
  `Date` TIMESTAMP NOT NULL,
  `BabyID` INT NOT NULL,
  PRIMARY KEY (`HistoryID`),
  INDEX `BabyID_idx` (`BabyID` ASC),
  CONSTRAINT `BabyID`
    FOREIGN KEY (`BabyID`)
    REFERENCES `behbes`.`Baby` (`BabyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `behbes`.`SymptomHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`SymptomHistory` ;

CREATE TABLE IF NOT EXISTS `behbes`.`SymptomHistory` (
  `HistoryID` INT NOT NULL,
  `SymptomID` INT NOT NULL,
  PRIMARY KEY (`HistoryID`, `SymptomID`),
  INDEX `SymptomID_idx` (`SymptomID` ASC),
  CONSTRAINT `SympID`
    FOREIGN KEY (`SymptomID`)
    REFERENCES `behbes`.`Symptoms` (`SymptomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `HistID`
    FOREIGN KEY (`HistoryID`)
    REFERENCES `behbes`.`History` (`HistoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `behbes`.`MessageRoom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`MessageRoom` ;

CREATE TABLE IF NOT EXISTS `behbes`.`MessageRoom` (
  `MessageRoomID` INT NOT NULL AUTO_INCREMENT, 
  `CreationDate` TIMESTAMP NULL,
  `CreatorID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`MessageRoomID`),
  INDEX `UserID_idx` (`CreatorID` ASC),
  CONSTRAINT `CreatorID`
    FOREIGN KEY (`CreatorID`)
    REFERENCES `behbes`.` Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `behbes`.`Message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `behbes`.`Message` ;

CREATE TABLE IF NOT EXISTS `behbes`.`Message` (
  `MessageID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UserID` INT UNSIGNED NULL,
  `MessageRoomID` INT NULL,
  `MessageText` VARCHAR(140) NULL,
  `SendTime` TIMESTAMP NULL,
  PRIMARY KEY (`MessageID`),
  INDEX `MessageRoomID_idx` (`MessageRoomID` ASC),
  INDEX `UserID_idx` (`UserID` ASC),
  CONSTRAINT `MessageRoomID`
    FOREIGN KEY (`MessageRoomID`)
    REFERENCES `behbes`.`MessageRoom` (`MessageRoomID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SenderID`
    FOREIGN KEY (`UserID`)
    REFERENCES `behbes`.` Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
